services:
  downloadcenter:
    build:
      # Docker klont direkt das öffentliche GitHub-Repo
      context: "https://github.com/berto-1974/Downloadcenter.git#main"
    container_name: downloadcenter
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PORT: 3001
    volumes:
      - dc_uploads:/app/uploads
      - dc_database:/app/database

volumes:
  dc_uploads:
  dc_database:
